name       : layer-shell-qt
version    : 5.23.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.3/layer-shell-qt-5.23.3.tar.xz : 4a84038847e95559ecd0258e715e5c7b51dd758ed8676d3b56e99c5414b8c797
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
