name       : layer-shell-qt
version    : 5.23.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.2/layer-shell-qt-5.23.2.tar.xz : 8fc29b2cd8c7f4ff2ce2fb9de495673e0778af2125e63aa1c1d295775e98895f
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
