name       : layer-shell-qt
version    : 5.23.4
release    : 9
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.4/layer-shell-qt-5.23.4.tar.xz : 53c4106dbba50ace8c4c0e1e2739a1b190797e2b0a48725b88bdcbd1f9d1e428
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
