name       : layer-shell-qt
version    : 5.22.1
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.22.1/layer-shell-qt-5.22.1.tar.xz : 60314e0b4253e4b8ce8359935b29659ac45d19f21941e771a7bc28a824b5a1d6
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
