name       : layer-shell-qt
version    : 5.23.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.1/layer-shell-qt-5.23.1.tar.xz : c79c2306ee9f6a672612b37f28074609748f5570b7785d4096e5573f12fb9e0a
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
