name       : layer-shell-qt
version    : 5.24.3
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.3/layer-shell-qt-5.24.3.tar.xz : 5de105ece2d7e6ca2d65305186462b0f9240930276adf7d5eedf77ffeaa67d40
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
