name       : layer-shell-qt
version    : 5.25.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/layer-shell-qt-5.25.3.tar.xz : 60c5172a66562f1a12b8d27bc632e80eb721fb7dab89c5f3d7ac12c849c53d1b
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
