name       : layer-shell-qt
version    : 5.27.7
release    : 23
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/layer-shell-qt-5.27.7.tar.xz : 27c44e7db73bf2aa6728719e8bb848c1b0c1c7a704c86349a419577920c6f421
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kwayland-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
